INSERT INTO FILMS(id,title, opening_crawl, director, producer, release_date)
VALUES (NEXTVAL('HIBERNATE_SEQUENCE'),
        'A New Hope',
		'It is a period of civil war. Rebel spaceships, striking from a hidden base, have won their first victory against the evil Galactic Empire.  During the battle, Rebel spies managed to steal secret plans to the Empires ultimate weapon, the DEATH STAR, an armored space station with enough power to destroy an entire planet.  Pursued by the Empires sinister agents, Princess Leia races home aboard her starship, custodian of the stolen plans that can save her people and restore freedom to the galaxy....',
		'George Lucas',
		'Gary Kurtz, Rick McCallum',
		'1977-05-25'),
		(NEXTVAL('HIBERNATE_SEQUENCE'),
                'Return of the Jedi',
        		'Luke Skywalker has returned to his home planet of Tatooine in an attempt to rescue his friend Han Solo from the clutches of the vile gangster Jabba the Hutt.  Little does Luke know that the GALACTIC EMPIRE has secretly begun construction on a new armored space station even more powerful than the first dreaded Death Star.  When completed, this ultimate weapon will spell certain doom for the small band of rebels struggling to restore freedom to the galaxy...',
        		'Richard Marquand',
        		'Howard G. Kazanjian, George Lucas, Rick McCallum',
        		'1980-05-17'),
        (NEXTVAL('HIBERNATE_SEQUENCE'),
                        'The Phantom Menace',
                        'Turmoil has engulfed the Galactic Republic. The taxation of trade routes to outlying star systems is in dispute.  Hoping to resolve the matter with a blockade of deadly battleships, the greedy Trade Federation has stopped all shipping to the small planet of Naboo.  While the Congress of the Republic endlessly debates this alarming chain of events, the Supreme Chancellor has secretly dispatched two Jedi Knights, the guardians of peace and justice in the galaxy, to settle the conflict....',
                        'George Lucas',
                        'Rick McCallum',
                        '1999-05-19');