DROP TABLE IF EXISTS FILMS;

CREATE TABLE FILMS (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(250) NOT NULL,
  opening_crawl VARCHAR(500) NOT NULL,
  director VARCHAR(250) NOT NULL,
  producer VARCHAR(250) NOT NULL,
  release_date VARCHAR(250) NOT NULL,
  created DATE DEFAULT now(),
  edited DATE DEFAULT NULL,
  version INT DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE SEQUENCE HIBERNATE_SEQUENCE
  START WITH 1
  INCREMENT BY 1;
